/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppShopIndexRouteImport } from './routes/_app.shop.index'
import { Route as AppShopSlugRouteImport } from './routes/_app.shop.$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppShopIndexRoute = AppShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => AppRoute,
} as any)
const AppShopSlugRoute = AppShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/shop/$slug': typeof AppShopSlugRoute
  '/shop/': typeof AppShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/shop/$slug': typeof AppShopSlugRoute
  '/shop': typeof AppShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/shop/$slug': typeof AppShopSlugRoute
  '/_app/shop/': typeof AppShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shop/$slug' | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shop/$slug' | '/shop'
  id: '__root__' | '/_app' | '/_app/' | '/_app/shop/$slug' | '/_app/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop/': {
      id: '/_app/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof AppShopIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop/$slug': {
      id: '/_app/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof AppShopSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppShopSlugRoute: typeof AppShopSlugRoute
  AppShopIndexRoute: typeof AppShopIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppShopSlugRoute: AppShopSlugRoute,
  AppShopIndexRoute: AppShopIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
