/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCheckoutRouteImport } from './routes/_app.checkout'
import { Route as AppShopIndexRouteImport } from './routes/_app.shop.index'
import { Route as AppShopSlugRouteImport } from './routes/_app.shop.$slug'
import { Route as AppOrderOrderIdRouteImport } from './routes/_app.order.$orderId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppShopIndexRoute = AppShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => AppRoute,
} as any)
const AppShopSlugRoute = AppShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderOrderIdRoute = AppOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/checkout': typeof AppCheckoutRoute
  '/order/$orderId': typeof AppOrderOrderIdRoute
  '/shop/$slug': typeof AppShopSlugRoute
  '/shop/': typeof AppShopIndexRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof AppCheckoutRoute
  '/': typeof AppIndexRoute
  '/order/$orderId': typeof AppOrderOrderIdRoute
  '/shop/$slug': typeof AppShopSlugRoute
  '/shop': typeof AppShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/': typeof AppIndexRoute
  '/_app/order/$orderId': typeof AppOrderOrderIdRoute
  '/_app/shop/$slug': typeof AppShopSlugRoute
  '/_app/shop/': typeof AppShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout' | '/order/$orderId' | '/shop/$slug' | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to: '/checkout' | '/' | '/order/$orderId' | '/shop/$slug' | '/shop'
  id:
    | '__root__'
    | '/_app'
    | '/_app/checkout'
    | '/_app/'
    | '/_app/order/$orderId'
    | '/_app/shop/$slug'
    | '/_app/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop/': {
      id: '/_app/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof AppShopIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop/$slug': {
      id: '/_app/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof AppShopSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/order/$orderId': {
      id: '/_app/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof AppOrderOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrderOrderIdRoute: typeof AppOrderOrderIdRoute
  AppShopSlugRoute: typeof AppShopSlugRoute
  AppShopIndexRoute: typeof AppShopIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckoutRoute: AppCheckoutRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrderOrderIdRoute: AppOrderOrderIdRoute,
  AppShopSlugRoute: AppShopSlugRoute,
  AppShopIndexRoute: AppShopIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
